version: '3'
services:
    cron_telegram:
        image: registry.gitlab.com/riszkymf/cron_telegram
        network_mode: bridge
        environment:
            - CRON_MIN=*/1
            - CRONJOB_COMMAND=cd /code && python3 /code/app.py

    