version: '3'
services:
    cron_telegram:
        image: crontol
        network_mode: host
        environment:
            - CRON_MIN=*/1
            - CRONJOBS_FILE=crontab/cron
            - CRONJOB_COMMAND=cd /code && python3 /code/app.py
        volumes:
            - ./log:/code/log
            - ./crontab:/var/spool/cron/crontabs
    